### ISSUE TITLE
Suggest improvement

### ISSUE THREAD

**Issue by HenryZerocool** [matt-ross16/CheckMyLinks#8]
Everything works fine

Hopefully this:
`python checkMyURL.py <your URL here>`
Can become this:
`python checkMyURL.py <filename>`

**Comment by matt-ross16** [comment]
Is this for the README?

At the moment, I have 3 different ways to use this program.

1) Entering a single URL for inspection
2) Entering a URL to be opened and parsed for broken links
3) Entering a file to be opened and parsed for broken links

The option you are pointing out here is for inputting just a single URL and checking its status without opening it, so I intend on it to be used with a URL input, not a filename.

**Comment by HenryZerocool** [comment]
I pulled most recent version 10 minutes ago, and I still have the same problem

This `python checkMyURL.py <your URL here>` works fine

But this `python checkMyURL.py .\links.txt` gave me errors

![image](https://user-images.githubusercontent.com/38387918/94503833-6212e780-01d5-11eb-9e27-cc5a4313491f.png)

Since it said invalid link, I'm assuming it's only expecting URL 

EDIT: Oh, I just read the updated Readme, don't worry about this. You are doing great :D

**Comment by matt-ross16** [comment]
Thanks! Yeah, I had it set where only based on the options given that it would actually parse a physical file. Thanks for the catch though!
